### ISSUE TITLE
[StoreCache] "Cache update" hat ein Problem festgestellt

### ISSUE THREAD

**Issue by fb71** [Mapzone/mapzone-atlas-plugin#12]
[ERROR] LogAdapter             : Die Aktion "Cache update" hat ein Problem festgestellt und musste erfolglos abgebrochen werden.
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.lucene.util.SetOnce$AlreadySetException: The object cannot be set twice!
	at org.polymap.core.data.rs.RDataStore.deleteSchema(RDataStore.java:353)
	at org.polymap.core.data.rs.RDataStore.removeSchema(RDataStore.java:143)
	at org.polymap.core.data.feature.storecache.FullDataStoreSyncStrategy$SyncJob.runWithException(FullDataStoreSyncStrategy.java:135)
	at org.polymap.core.runtime.UIJob.lambda$0(UIJob.java:232)
	at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:67)
	at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:41)
	at org.eclipse.rap.rwt.lifecycle.UICallBack.runNonUIThreadWithFakeContext(UICallBack.java:54)
	at org.polymap.core.runtime.session.RapSessionContextProvider$RapSessionContext.execute(RapSessionContextProvider.java:132)
	at org.polymap.core.runtime.UIJob.run(UIJob.java:228)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.lucene.util.SetOnce$AlreadySetException: The object cannot be set twice!
	at org.polymap.core.data.rs.RFeatureStore.removeFeatures(RFeatureStore.java:437)
	at org.polymap.core.data.rs.RDataStore.deleteSchema(RDataStore.java:349)
	... 9 more
Caused by: java.lang.RuntimeException: org.apache.lucene.util.SetOnce$AlreadySetException: The object cannot be set twice!
	at org.polymap.recordstore.lucene.LuceneRecordStore$LuceneUpdater.<init>(LuceneRecordStore.java:564)
	at org.polymap.recordstore.lucene.LuceneRecordStore.prepareUpdate(LuceneRecordStore.java:519)
	at org.polymap.core.data.rs.RFeatureStore$TransactionState.lambda$0(RFeatureStore.java:494)
	at org.polymap.core.runtime.LockedLazyInit.get(LockedLazyInit.java:53)
	at org.polymap.core.runtime.LazyInit.get(LazyInit.java:65)
	at org.polymap.core.data.rs.RFeatureStore$TransactionState.updater(RFeatureStore.java:497)
	at org.polymap.core.data.rs.RFeatureStore.removeFeatures(RFeatureStore.java:425)
	... 10 more
Caused by: org.apache.lucene.util.SetOnce$AlreadySetException: The object cannot be set twice!
	at org.apache.lucene.util.SetOnce.set(SetOnce.java:69)
	at org.apache.lucene.index.MergePolicy.setIndexWriter(MergePolicy.java:269)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1090)
	at org.polymap.recordstore.lucene.LuceneRecordStore$LuceneUpdater.<init>(LuceneRecordStore.java:551)
	... 16 more

**Comment by fb71** [comment]
Die Umstellung auf asynchronen StoreCache hat das behoben.
