### ISSUE TITLE
Unable to set visibility of layer

### ISSUE THREAD

**Issue by fb71** [Mapzone/mapzone-atlas-plugin#13]
Unable to set visibility of layer.
java.util.concurrent.CompletionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.net.SocketTimeoutException: connect timed out
	at org.polymap.p4.layer.FeatureLayer.lambda$4(FeatureLayer.java:121)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.polymap.p4.layer.FeatureLayer.lambda$0(FeatureLayer.java:115)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at org.polymap.core.runtime.JobExecutor$2.runWithException(JobExecutor.java:103)
	at org.polymap.core.runtime.UIJob.lambda$0(UIJob.java:232)
	at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:67)
	at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:41)
	at org.eclipse.rap.rwt.lifecycle.UICallBack.runNonUIThreadWithFakeContext(UICallBack.java:54)
	at org.polymap.core.runtime.session.RapSessionContextProvider$RapSessionContext.execute(RapSessionContextProvider.java:132)
	at org.polymap.core.runtime.UIJob.run(UIJob.java:228)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.net.SocketTimeoutException: connect timed out
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.polymap.p4.catalog.AllResolver.resolve(AllResolver.java:238)
	at org.polymap.p4.catalog.AllResolver.serviceInfo(AllResolver.java:184)
	at org.polymap.p4.catalog.AllResolver.connectLayer(AllResolver.java:141)
	at org.polymap.p4.layer.FeatureLayer.doConnectLayer(FeatureLayer.java:185)
	at org.polymap.p4.layer.FeatureLayer.lambda$4(FeatureLayer.java:118)
	... 11 more
Caused by: java.lang.RuntimeException: java.net.SocketTimeoutException: connect timed out
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at org.polymap.p4.catalog.AllResolver.lambda$3(AllResolver.java:253)
	... 9 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at org.geotools.data.ows.SimpleHttpClient.get(SimpleHttpClient.java:100)
	at org.geotools.data.ows.AbstractOpenWebService.internalIssueRequest(AbstractOpenWebService.java:442)
	at org.geotools.data.wms.WebMapServer.issueRequest(WebMapServer.java:435)
	at org.geotools.data.ows.AbstractOpenWebService.negotiateVersion(AbstractOpenWebService.java:272)
	at org.geotools.data.ows.AbstractOpenWebService.<init>(AbstractOpenWebService.java:120)
	at org.geotools.data.ows.AbstractOpenWebService.<init>(AbstractOpenWebService.java:100)
	at org.geotools.data.ows.AbstractOpenWebService.<init>(AbstractOpenWebService.java:78)
	at org.geotools.data.wms.WebMapServer.<init>(WebMapServer.java:372)
	at org.polymap.core.data.wms.catalog.WmsServiceInfo.of(WmsServiceInfo.java:55)
	at org.polymap.core.data.wms.catalog.WmsServiceResolver.resolve(WmsServiceResolver.java:49)
	at org.polymap.p4.catalog.AllResolver.lambda$3(AllResolver.java:249)

**Comment by fb71** [comment]
Das Update vom StoreCache kam der Liste in die Quere. Da StoreCache jetzt asynchron aktualisiert wird, tritt dieses Problem nicht mehr auf.
