### ISSUE TITLE
[StoreCache] Cache Update: Bodenrichtwerte

### ISSUE THREAD

**Issue by fb71** [Mapzone/mapzone-atlas-plugin#14]
[INFO]  BatikProgressProvider  : [PROGRESS] Cache update - subtask: Fetching
Apr 12, 2018 4:34:43 PM org.geotools.xml.impl.HTTPURIHandler getConnection
INFO: http://geoportal-vg.de/geoserver/atlas/wfs?service=WFS&version=2.0.0&request=DescribeFeatureType&typeName=atlas%3Abodenrichtwerte_bauland
[WARN]  FullDataStoreSyncStr...: 
java.lang.RuntimeException: java.lang.NullPointerException
	at org.polymap.core.data.rs.RFeatureStore.addFeatures(RFeatureStore.java:295)
	at org.polymap.core.data.feature.storecache.FullDataStoreSyncStrategy$SyncJob.runWithException(FullDataStoreSyncStrategy.java:153)
	at org.polymap.core.runtime.UIJob.lambda$0(UIJob.java:232)
	at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:67)
	at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:41)
	at org.eclipse.rap.rwt.lifecycle.UICallBack.runNonUIThreadWithFakeContext(UICallBack.java:54)
	at org.polymap.core.runtime.session.RapSessionContextProvider$RapSessionContext.execute(RapSessionContextProvider.java:132)
	at org.polymap.core.runtime.UIJob.run(UIJob.java:228)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.NullPointerException
	at org.geotools.data.ReTypeFeatureReader.typeAttributes(ReTypeFeatureReader.java:146)
	at org.geotools.data.ReTypeFeatureReader.<init>(ReTypeFeatureReader.java:100)
	at org.geotools.data.wfs.WFSFeatureSource.getReaderInternal(WFSFeatureSource.java:275)
	at org.geotools.data.wfs.WFSFeatureStore.getReaderInternal(WFSFeatureStore.java:154)
	at org.geotools.data.store.ContentFeatureSource.getReader(ContentFeatureSource.java:647)
	at org.geotools.data.store.ContentFeatureSource.accepts(ContentFeatureSource.java:805)
	at org.geotools.data.store.ContentFeatureCollection.accepts(ContentFeatureCollection.java:129)
	at org.polymap.core.data.rs.RFeatureStore.addFeatures(RFeatureStore.java:251)
	... 8 more

**Comment by fb71** [comment]
Kann ich nicht mehr nachvollziehen. Ich schließe das erstmal.
