### ISSUE TITLE
[StoreCache] column reference "ausschreibung" is ambiguous

### ISSUE THREAD

**Issue by fb71** [Mapzone/mapzone-atlas-plugin#15]
Ich glaube wir brauchen:

  - einen async Job für Cache-Update (für performance und parallel Probleme)
  - und/oder joinAndDispatch() beim update
  
-----------------------------------------------------------------
[INFO]  BatikProgressProvider  : [PROGRESS] Cache update - subtask: Fetching
Apr 17, 2018 5:29:06 PM org.geotools.data.ows.AbstractOpenWebService internalIssueRequest
SEVERE: Failed to execute request http://geoportal-vg.de/geoserver/atlas/wfs?REQUEST=GetFeature&VERSION=2.0.0&SERVICE=WFS
[WARN]  FullDataStoreSyncStr...: 
org.geotools.data.wfs.internal.WFSException: WFS returned an exception. Originating Request: GET_FEATURE[
	handle: GeoTools 18.1(306cf3bdde1bee0110dc1c3ba77819f1e294a45b) WFS 2.0.0 DataStore @hetzner2#1
	outputFormat: <application/gml+xml; version=3.2>
	method: POST
	onlineResource: <http://geoportal-vg.de/geoserver/atlas/wfs?>
	final URL: <http://geoportal-vg.de/geoserver/atlas/wfs?REQUEST=GetFeature&VERSION=2.0.0&SERVICE=WFS>
]
	[NoApplicableCode: [java.lang.RuntimeException: java.io.IOException
java.io.IOExceptionorg.postgresql.util.PSQLException: ERROR: column reference &quot;ausschreibung&quot; is ambiguous
  Position: 48
ERROR: column reference &quot;ausschreibung&quot; is ambiguous
  Position: 48]]
	at org.geotools.data.wfs.internal.parsers.AbstractGetFeatureResponseParserFactory.parseException(AbstractGetFeatureResponseParserFactory.java:214)
	at org.geotools.data.wfs.internal.parsers.AbstractGetFeatureResponseParserFactory.createResponse(AbstractGetFeatureResponseParserFactory.java:160)
	at org.geotools.data.wfs.internal.WFSRequest.createResponse(WFSRequest.java:220)
	at org.geotools.data.wfs.internal.WFSRequest.createResponse(WFSRequest.java:38)
	at org.geotools.data.ows.AbstractOpenWebService.internalIssueRequest(AbstractOpenWebService.java:445)
	at org.geotools.data.wfs.internal.WFSClient.internalIssueRequest(WFSClient.java:298)
	at org.geotools.data.wfs.internal.WFSClient.issueRequest(WFSClient.java:338)
	at org.geotools.data.wfs.WFSFeatureSource.getReaderInternal(WFSFeatureSource.java:256)
	at org.geotools.data.wfs.WFSFeatureStore.getReaderInternal(WFSFeatureStore.java:154)
	at org.geotools.data.store.ContentFeatureSource.getReader(ContentFeatureSource.java:647)
	at org.geotools.data.store.ContentFeatureSource.accepts(ContentFeatureSource.java:805)
	at org.geotools.data.store.ContentFeatureCollection.accepts(ContentFeatureCollection.java:129)
	at org.polymap.core.data.rs.RFeatureStore.addFeatures(RFeatureStore.java:251)
	at org.polymap.core.data.feature.storecache.FullDataStoreSyncStrategy$SyncJob.runWithException(FullDataStoreSyncStrategy.java:153)
	at org.polymap.core.runtime.UIJob.lambda$0(UIJob.java:232)
	at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:67)
	at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:41)
	at org.eclipse.rap.rwt.lifecycle.UICallBack.runNonUIThreadWithFakeContext(UICallBack.java:54)
	at org.polymap.core.runtime.session.RapSessionContextProvider$RapSessionContext.execute(RapSessionContextProvider.java:132)
	at org.polymap.core.runtime.UIJob.run(UIJob.java:228)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by fb71** [comment]
Mit den letzten Commits gibt es jetzt einen async Job für das Updates des Caches.
